TKO-37 -- FE: Create student profile template (functionality does not really need to work yet)
csuntechlab/takeoff pull request #11
Opened 2019-03-13 17:52 UTC by alecnicolas

# Description
- Created student profile view (functionality not implemented yet)
- Added navbar to the application (styling yet to be determined)  

# Testing
Navigate to `/profile` and ensure the page is responsive.

# Installation
Probably not, but `yarn install` if you run into problems.

2019-03-13 19:54 UTC, andrewMETALAB requested changes
Overall great work.

(1) I left some comments throughout the code. All stuff related to the grid. (You were nesting grid columns/rows unnecessarily).

(2) Bootstrap already gives us breakpoint variables. Please remove your $break-xx variables and instead use bootstraps:  https://getbootstrap.com/docs/4.3/layout/overview/#responsive-breakpoints

(3) Maybe instead of nesting a `<strong>` tag inside each div with a class of "profile-info__header", you could just set the ".profile-info__header" to have "font-weight:bold"

(4) Maybe current-interests doesnt need to be it's own component? I think it could just be part of the profile-info component? (It seems to me to be part of the profile-info section). 

(5) font-sizes seem way too small to me on small viewports. I don't think we should ever go below 16px for font-sizes, regardless of viewport width.

2019-03-13 19:54 UTC, andrewMETALAB commented on resources/js/components/studentProfile/StudentPhoto.vue
> +	<div class="row justify-content-end py-3 px-2">
You don't need this div or the next one. Just move the "py-3 px-2" to this element's parent instead. 👍

2019-03-13 19:54 UTC, andrewMETALAB commented on resources/js/components/studentProfile/BadgesEarned.vue
> +	<div class="row">
You don't need this div or the following one. Grid stuff has already been handled in the parent.

2019-03-13 19:54 UTC, andrewMETALAB commented on resources/js/components/studentProfile/CurrentInterests.vue
> +	<div class="row">
You don't need this div or the following one. Grid stuff has already been handled in the parent.

2019-03-13 19:54 UTC, andrewMETALAB commented on resources/js/components/studentProfile/ProfileInfo.vue
> +	<div class="row">
You don't need this div or the following one. Grid stuff has already been handled in the parent.

2019-03-15 19:28 UTC, raimahossain approved these changes
visually everything looks gooooosh!

2019-03-18 16:21 UTC, andrewMETALAB approved these changes
Great work 👍

2019-03-18 16:21 UTC, merged