HOTFIX -- Updated the gitignore
csuntechlab/takeoff pull request #12
Opened 2019-03-13 18:38 UTC by alecnicolas

# Description
Put the gitignore to use

2019-03-13 19:06 UTC, andrewMETALAB requested changes
I believe that this hotfix is not necessary, as the .gitignore file was updated in Lauren's branch (with Nerces's help) which was already merged into dev 👍

2019-03-13 19:22 UTC, andrewMETALAB approved these changes

2019-03-13 23:08 UTC, ebm17915 commented
From my understanding you want to add the docker-compose.yml to gitignore so you can change ports in order to have multiple containers up without fear of pushing changes right? Personally I think it's fine, but I occasionally do changes on it (add DB connections) so I prefer not to "unignore" it each time :).

2019-03-15 16:53 UTC, ebm17915 approved these changes
You're welcome 👍

2019-03-15 16:59 UTC, merged