TKO-21: add passport to project:
csuntechlab/takeoff pull request #14
Opened 2019-03-20 16:54 UTC by MikkalMc

WIP
# Description
'
Added Laravel Passport for oauth token generation and verification
See docs: https://laravel.com/docs/5.8/passport
'
  
# Testing
'tester should be able to hit the following routes to retrieve bearer tokens, register users and revoke bearer tokens: 
'
- /login
- /register
- /logout

# Installation
'Run a composer install and migrate '

2019-03-20 19:56 UTC, alecnicolas reviewed
Works for me 👍

2019-03-20 20:46 UTC, ChanM0 commented on app/Http/Controllers/LoginController.php
> +class LoginController extends Controller
May want to rename to include the idea that logout is in here, couldnt tell by just the name.

2019-03-20 21:11 UTC, ChanM0 commented on app/Http/Controllers/LoginController.php
> +        $request->validate([
Same as register should have a Request Object defining the rules and the return messages. Want to make a test for this.

2019-03-20 21:11 UTC, ChanM0 commented on app/Services/LoginService.php
> +        if(!Auth::attempt($credentials))
middle wear around api route does this already.

2019-03-20 21:11 UTC, ChanM0 commented on app/Services/LoginService.php
> +            $user = $request->user();
Use Auth::user();

2019-03-21 18:23 UTC, MikkalMc commented on app/Http/Controllers/LoginController.php
> +        $request->validate([
task made to address this

2019-03-21 22:09 UTC, alecnicolas approved these changes
idk what changed but it still works for me so

2019-03-25 19:14 UTC, luisjg commented on app/Services/RegisterService.php
> +            $name = (string)$request['name'];
Aren't these strings already?

2019-03-25 19:16 UTC, luisjg commented on app/Services/RegisterService.php
> +        try {
There's a createOrFail function or you can surround this in a database transaction -> https://laravel.com/docs/5.8/database#database-transactions

2019-03-25 19:16 UTC, luisjg commented on resources/js/api/Auth.js
> +        console.log(response.data);
Console logs....

2019-03-25 19:17 UTC, luisjg requested changes
See comments.

2019-03-29 19:20 UTC, luisjg approved these changes
👍

2019-03-29 19:30 UTC, merged