TKO 64: BE: Create Users Table
csuntechlab/takeoff pull request #22
Opened 2019-03-29 17:46 UTC by nixy97

# Description
Added first_name and last_name attributes to the Users table
  
# Testing
run php artisan migrate:fresh to see the new attributes

# Installation
'Are there any dependencies the reviewer needs to download?'

2019-04-02 17:19 UTC, MikkalMc reviewed
We need to remove the 'name' field within this model and just stick to first_name and last_name

2019-04-02 17:20 UTC, MikkalMc requested changes
Remove name field

2019-04-02 17:22 UTC, MikkalMc requested changes

2019-04-02 17:22 UTC, MikkalMc commented on database/migrations/2014_10_12_000000_create_users_table.php
>              $table->string('name');
Remove the name field in migration plozz,

2019-04-02 17:22 UTC, MikkalMc commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->string('first_name')->nullable();
by introducing these, we will also need to update the registration service :+1:

2019-04-03 16:41 UTC, alecnicolas approved these changes
Good, just make Mikkal's changes

2019-04-09 18:47 UTC, MikkalMc approved these changes
cool beans

2019-04-09 18:47 UTC, merged