TKO-55: BE: Student Filter by Grad Date
csuntechlab/takeoff pull request #29
Opened 2019-04-05 18:00 UTC by nixy97

# Description
Create a Route to filter students based on grad date, given an email
  
# Testing
on this branch go on http://localhost:8080/students/graddate/Spring2019 
it should give an empty array

# Installation
composer install

2019-04-05 23:56 UTC, MikkalMc approved these changes

2019-04-06 00:05 UTC, MikkalMc requested changes
admin contract not found

2019-04-09 17:24 UTC, MikkalMc approved these changes

2019-04-09 17:43 UTC, luisjg approved these changes
👍

2019-04-09 18:24 UTC, merged