TKO-71 -- FE: Fix Babel Object Spread bug
csuntechlab/takeoff pull request #33
Opened 2019-04-08 22:16 UTC by alecnicolas

# Description
Babel was throwing an error which was only causing problems when trying to use the object spread syntax.
  
# Testing
I put a random '...mapGetters' into the project.
`yarn run dev` should NOT error out. That's how you know it's fixed.

# Installation
`yarn install`
If that doesn't work, let me know

2019-04-09 17:26 UTC, MikkalMc requested changes
Simply modifying the node modules is a temporary solution, since node modules will be modified every time we run an install command.

2019-04-10 17:06 UTC, andrewMETALAB requested changes
Ok. So the bug only got fixed when I manually moved that folder in node_modules.
Like Mikkal said, this is not a solution, since git doesn't track anything inside of node_modules. :(

2019-04-10 22:26 UTC, andrewMETALAB approved these changes
WOOOO!!!
Nasty bug. 
Good work.

2019-04-11 16:55 UTC, MikkalMc approved these changes

2019-04-12 17:31 UTC, merged