TKO-57:BE: User searching by name
csuntechlab/takeoff pull request #46
Opened 2019-04-24 22:47 UTC by nixy97

# Description
when passed in the name of a user, it returns the user
  
# Testing
First add the route 'api/students/search' to the VerifyCsrfToken middleware 
Test the route on postman, put name as the key on the form-data and the name of a person on your database
This should return the user
 
# Installation
'Are there any dependencies the reviewer needs to download?'

2019-04-26 18:26 UTC, alecnicolas reviewed
The searching works for first and last name separately, but typing in a full name does not work.

Ex: `Josh` and `Magaleno` work but `Josh Magaleno` does not

2019-04-26 18:27 UTC, alecnicolas requested changes
Previously mentioned

2019-04-26 23:16 UTC, MikkalMc approved these changes

2019-05-03 17:26 UTC, alecnicolas approved these changes
👍

2019-05-04 00:07 UTC, merged