TKO-80 -- FE: Create an attendance sheet for the admin
csuntechlab/takeoff pull request #58
Opened 2019-05-03 23:53 UTC by raimahossain

# Description
Create an attendance sheet for the admin
  
# Testing
Go to /workshopview and see if the attendance sheet appears (including pagination)

2019-05-07 19:08 UTC, andrewMETALAB requested changes
I'm getting several console errors including:
`[Vue warn]: Property or method "user" is not defined on the instance but referenced during render...`
`TypeError: "_vm.user is undefined"`

Also getting a terminal error when running the watch command:
`Error: [BABEL] /Users/andrewgrano/websites/takeoff/resources/js/app.js: The `core-js` version must be false, 2 or 3, but got true...`

Are you *not* seeing these errors? If so, maybe me .env is out of date?

2019-05-08 23:14 UTC, andrewMETALAB requested changes
See my comment bellow 👍

2019-05-08 23:14 UTC, andrewMETALAB commented on resources/js/router/views/WorkshopView/index.vue
> +            <AttendanceCard/>
Raima, this line is what was producing the JS console error! Just remove this line and you'll be good to go. 👍

2019-05-20 19:40 UTC, andrewMETALAB approved these changes

2019-05-20 22:38 UTC, alecnicolas approved these changes
y35

2019-05-20 22:48 UTC, merged