TKO-109 -- FE: Connect front end auth to back end (login and signup)
csuntechlab/takeoff pull request #63
Opened 2019-05-16 00:18 UTC by alecnicolas

# Description
Handled all logic between the frontend and backend for admin/user login and registration.
  
# Testing
Invite a student using your email and go through registration as that student. Logout then log in as that student again. Repeat for admin.

2019-05-16 18:33 UTC, MikkalMc requested changes
if we're gonna change certain areas in the back end we have to also update the tests

2019-05-16 19:33 UTC, alecnicolas commented
> if we're gonna change certain areas in the back end we have to also update the tests

yes

2019-05-20 15:57 UTC, MikkalMc approved these changes

2019-05-20 16:35 UTC, luisjg approved these changes
👍

2019-05-20 16:37 UTC, merged