TKO-83 -- FE: Workshop display page (Admin/User)
csuntechlab/takeoff pull request #65
Opened 2019-05-17 18:50 UTC by raimahossain

# Description
Create a Workshop display page for admin according to the new mockup
  
# Testing
Created the basic Workshop display page for admin according to the new mockup

# Installation
Naw

2019-05-17 20:35 UTC, andrewMETALAB approved these changes

2019-05-20 16:29 UTC, MikkalMc requested changes

2019-05-20 16:29 UTC, MikkalMc commented on resources/js/router/views/Workshop/index.vue
> +            <router-link to="/workshop-creation" type="submit" class="btn btn-primary">Create Workshop</router-link>
This button looks weird

2019-05-20 22:20 UTC, MikkalMc approved these changes

2019-05-20 22:21 UTC, merged